### ISSUE TITLE
How to sample the 600 instances from Nuscenes?

### ISSUE THREAD

**Issue by flymin** [alexanderswerdlow/BEVGen#1]
Hi,

In your paper, you said "We sample 4 images from each scene, with 600 instances overall" for Nuscenes. However, there are only 500 tokens in [data/interesting_image_tokens.txt](https://github.com/alexanderswerdlow/bevgen/blob/master/data/interesting_image_tokens.txt) and most of them come from `sweeps` rather than keyframes. Could you please provide more details about how to perform the evaluation on the Nuscenes?

Thanks.

**Comment by alexanderswerdlow** [comment]
Hi @flymin!

Please try this [pickle file](https://go.aswerdlow.com/AHWr++6C). It should load a python list with a simple `pickle.load()`. Please let me know if it works for you and if so, I'll upload it to the repo.

**Comment by flymin** [comment]
> Hi @flymin!
> 
> Please try this [pickle file](https://go.aswerdlow.com/AHWr++6C). It should load a python list with a simple `pickle.load()`. Please let me know if it works for you and if so, I'll upload it to the repo.

Thanks! In this pickle file, there are 602 tokens for keyframes from the CAM_FRONT channel. Is it the subset you used for Table 1?

**Comment by alexanderswerdlow** [comment]
Yes, that was the subset used. 600 was a mistake. The code to generate the subset took every 10th keyframe and I think nuScenes validation isn't exactly 6k leading to the weird 602 number.

**Comment by flymin** [comment]
Yes, it makes sense. Thank you.
