### ISSUE TITLE
About visualization

### ISSUE THREAD

**Issue by Andy-zd** [alexanderswerdlow/BEVGen#2]
Hi,

I am wondering how to visualize the bev map in this codebase. It seems that the script of  ./multi_view_generation/bev_utils/visualize.py cannot work well. 

Thanks in advance.

**Comment by alexanderswerdlow** [comment]
Hi @Andy-zd!

This was the visualization code that was used to generate the figures in the paper. It might require some modifications to work for your use-case but it's what I used. There are some other functions (e.g., `colorize` in `nuscenes_helper.py`) that are alternatives (but work differently).

**Comment by Andy-zd** [comment]
Great. Thanks for your suggestion.
