### ISSUE TITLE
Training code

### ISSUE THREAD

**Issue by t-martyniuk** [alexanderswerdlow/BEVGen#3]
Hi, @alexanderswerdlow!

Thanks for your work! 

As it's mentioned throughout the README, but I couldn't find it in the repository itself, - are you planning on releasing the training code?

Looking forward to it!

**Comment by GallonDeng** [comment]
+1

**Comment by alexanderswerdlow** [comment]
I should be able to provide it relatively shortly, sorry for the delay!

**Comment by alexanderswerdlow** [comment]
@AllenDun @t-martyniuk Training code is now available on this [branch](https://github.com/alexanderswerdlow/BEVGen/tree/training)! I plan to move it to master shortly but want to do some more verification before I do so. Feel free to let me know if anything is missing/broken on this branch and make a new issue and I'll see if I can fix it.
