### ISSUE TITLE
About the command "python multi_view_generation/scripts/argoverse_preprocess_all_cam.py"

### ISSUE THREAD

**Issue by NuanBaobao** [alexanderswerdlow/BEVGen#4]
Thanks for your work!
As it's mentioned throughout the README, we can run "python multi_view_generation/scripts/argoverse_preprocess_all_cam.py" to prepare train data, but I couldn't find the file named " argoverse_preprocess_all_cam.py " in the repository itself, are you planning on releasing the training code?
Looking forward to it!

**Comment by alexanderswerdlow** [comment]
Apologies, this should be `argoverse_preprocess.py`. I went back to some very old commits and found out I simply renamed the file :)

Let me know if you have issues running the script!
