### ISSUE TITLE
how to generate BEV maps on nuScenes?

### ISSUE THREAD

**Issue by poodarchu** [alexanderswerdlow/BEVGen#7]

**Comment by alexanderswerdlow** [comment]
Hi @poodarchu! You should be able to use this [script](https://github.com/alexanderswerdlow/BEVGen/blob/1de1edffca0bc2640723562ef7a4111ff0f44836/multi_view_generation/scripts/figure_generator.py#L99) [might need some modification] which calls `viz_bev`. It's used in [several other places](https://github.com/search?q=repo%3Aalexanderswerdlow/BEVGen%20viz_bev&type=code) for reference
