### ISSUE TITLE
Training error

### ISSUE THREAD

**Issue by zhuhu00** [alexanderswerdlow/BEVGen#8]
When i use your training code on nuscenes dataset, it has some errors, like: 
https://github.com/alexanderswerdlow/BEVGen/blob/bca7c544a5c15736b3b454248b72f6300b433284/multi_view_generation/bev_utils/nuscenes_dataset.py#L542

maybe you should provide this code
![image](https://github.com/user-attachments/assets/52b07f93-8518-4300-a1e1-8f22acf9aff1)

**Comment by alexanderswerdlow** [comment]
Hi! I can't guarantee any of it runs at the moment, but feel free to take a look. `specific_metadrive_bev` is not the default setting so it shouldn't be necessary for training but hope it's helpful anyway!
[code.zip](https://github.com/user-attachments/files/17138251/code.zip)
